package com.ab.auth.exception;

public enum ErrorCode {
    INTERNAL_ERROR,
    USERS_FETCHING_ERROR,
    SAVE_DATA_IN_DB_ERROR,
    OTP_GENERATION_ERROR,
    INVALID_OTP,
    DEVICE_ID_NOT_FOUND,
    USER_ALREADY_EXISTS,
    PASSWORD_ENCODER_ERROR,
    CACHE_OPERATION_ERROR,
    USER_NOT_EXISTS,
    JWT_GENERATION_ERROR,
    JWT_EXPIRED_ERROR,
    INVALID_PASSWORD_ERROR,
    XSS_EXCEPTION

}
